WRONG_SCRIPTS = [
    ("😕", "Ay, mali yata ang linya... hindi ko po kilala 'yang tao na 'yan."),
    ("😤", "Uy, ilang beses na ba 'to? Wrong number na naman, ha!"),
    ("😴", "Hmm... *yawns* ...sino 'to? Mali number, matulog na nga ako ulit."),
    ("🎭", "HINDI. AKO. ANG. HINAHANAP. MO. Tapusin mo na 'yang paghahanap na 'yan!"),
    ("⏱️", "Sorry ha, wala akong panahon diyan, mali number 'to!"),
    ("🙏", "Pasensya na po, mali po yata ang tinawagan n'yo. Hindi po ako 'yan."),
    ("😏", "Aww, gusto mo ba talaga ako? Kasi hindi ako 'yung hinahanap mo, bes~"),
    ("🤨", "Bakit mo ko tinatawagan? Sino ka ba? Wala akong kinalaman diyan."),
    ("😨", "Ano?! Hindi, hindi ako 'yan! Wag mo kong idamay, please!"),
    ("😐", "...mali number. Bye."),
    ("😠", "GRABE KA, ilang beses ko nang sinasabing MALI NUMBER 'TO!"),
    ("😢", "Sana nga ako 'yung hinahanap mo... pero hindi. Paalam."),
    ("👵", "Iho, ang tanda ko na para makipaglaro sa mga bugtong n'yo. Mali 'yang number."),
    ("🧐", "Good day. This is not the individual you are attempting to reach. Please verify your records."),
    ("🥴", "Weeeh? Sinong 'to? Ay hindi... teka... hindi ako 'yan! *hic*"),
    ("🧒", "Hoy! Bata pa ko ah, wag mo ko tawagan, hindi kita kilala!"),
    ("🤑", "Oh hi! Bago tayo mag-usap, ikaw ba nanalo sa raffle? Ah wait, mali number pala 'to."),
    ("🤔", "Sino ba talaga tayo? Ang alam ko lang, hindi ako ang hinahanap mo."),
    ("😎", "Chill lang, bro. Mali lang number, walang bigyan."),
    ("😰", "Sino'ng nagbigay sa'yo ng number ko?! Hindi ako 'yan, layuan mo 'ko!"),
    ("😊", "Kamusta! Sayang, hindi ako 'yung hinahanap mo, pero kwentuhan pa rin tayo?"),
    ("🥱", "Ay iho, wala akong oras diyan, may mga anak akong iniintindi. Mali number 'to."),
    ("🕵️", "...hindi mo ako makikilala. At hindi ako ang hinahanap mo."),
    ("🙄", "Wow, ang galing mong humanap. Sayang, mali pa rin."),
    ("😬", "Uh... ah... hindi... hindi ako po siguro 'yan? Baka mali lang."),
    ("💅", "Naku, marami akong tagahanga, pero hindi ako 'yang pinaghahanap mo."),
    ("🙏", "Bless you, iho. Pero hindi ako ang hinahanap mo. Manalangin ka na lang."),
    ("😂", "Knock knock! Sino 'to? Ah, hindi pala ako 'yung joke mong hinahanap."),
    ("📏", "Ang dami ko nang pinapaalalahanan, at ito na naman— MALI. NUMBER."),
    ("🧘", "Huminga ka lang. Hindi ako siya. Subukan mo ulit maghanap."),
    ("🌟", "Alam mo bang bantay ako ng showbiz? Pero hindi, hindi ako 'yan."),
    ("💼", "Meeting pa 'to, wag mo 'ko idamay, mali number 'yan!"),
    ("👴", "Noong bata pa ako... ah teka, mali lang pala 'tong linyang 'to."),
    ("🚌", "Sabay-sabay tayo diyan pero hindi rin kita kilala, pre. Mali number."),
    ("🚨", "Uy, curfew na! At saka, hindi ako 'yang tinatawag mo."),
    ("😱", "OMG bakit ako tinatawagan?! Wag naman sanang ikaw yung ex ko... ay hindi pala, mali number lang."),
    ("😑", "Mali number. Wala nang iba."),
    ("😟", "Ay sayang, baka nasa panganib pa 'yung hinahanap mo. Pero hindi ako 'yan."),
    ("🎯", "Congratulations, tama ka sa pag-dial pero MALI sa sagot! Hindi ako 'yan!"),
    ("👀", "Sino ka ba? Bakit mo tinatawagan? May balita akong messy dyan sa inyo ha, pero hindi ako 'yan."),
    ("☔", "Maulan sa labas ngayon... at parang mali rin ang linyang dinial mo."),
    ("🔮", "Nakikita ko sa bituin... na hindi ako ang hinahanap mo."),
    ("📞", "Salamat sa pagtawag. Para sa maling number, pindutin ang... wait, wala palang option. Mali lang talaga 'to."),
    ("💀", "Bes, wrong number, no cap."),
    ("👻", "...may tumawag ba? ...MALI NUMBER. *phone drops*"),
    ("🍲", "Nagluluto ako ng sinigang, wag mo 'kong istorbohin, mali number 'yan!"),
    ("🌌", "Baka hindi lang ako ang mali dito... baka pati ang buong mundo. Pero oo, mali number."),
    ("🎙️", "Ito ang DJ ng gabi... at ito rin ang paalala— mali number 'to, iho!"),
    ("🩺", "Duty pa ko, wag mo 'ko tawagan ng ganito. Mali number 'to!"),
    ("👋", "Pasensya na, hindi nga ako 'yon. Ingat ka lagi. Paalam."),
    ("🤩", "Whoa, ang saya may tumatawag! Pero, uh... mali number 'to, sorry ha!"),
    ("☕", "Ano ba 'yan, ang aga-aga may tawag na... at mali pa number! Nakakainis."),
    ("🤖", "BEEP. Ito ay hindi ang numerong iyong hinahanap. BEEP."),
    ("😜", "Wag ka nang tumawag dito, hindi ako 'yung hinahanap mo. Mali number!"),
    ("🤫", "Shh... hindi ako pwedeng magsalita ngayon. Pero oo, mali 'yang number mo."),
    ("⚡", "AY GRABE ANG TAAS NG CAFFEINE KO— ah wait, mali number pala 'to, hi!"),
    ("🎶", "Purihin ang Panginoon... at saka, mali number 'to, anak."),
    ("🎮", "GG wrong number, chat. Di ako 'yung naghahanap mo."),
    ("🎧", "Magandang araw po! Paumanhin, hindi po kayo nakatawag sa tamang linya."),
    ("🎣", "Nasa dagat ako ngayon, pre. At mali ka rin ng huli— mali number 'yan."),
    ("📹", "Hi mga kaibigan— ay teka, may tumatawag. Ay, mali number lang pala. Sige, next vlog na lang!"),
    ("💐", "Aba, salamat sa pagtawag anak, pero mali yata ito. Ingat ka lagi ha."),
    ("🏀", "Timeout! Mali number 'to, tara ulit sa laro!"),
    ("🤷", "Sigurado ka ba diyan sa number na 'yan? Kasi mali 'yan."),
    ("💻", "Deadline pa 'to, wag mo 'kong istorbohin— at mali number pa!"),
    ("😈", "Akala mo ba ako 'yun? Hindi mo pa ako mahuhuli. MALI NUMBER."),
    ("👶", "Ga ga goo... (mommy: sorry, mali number po 'to, baby lang kasi 'to sa phone)."),
    ("🏄", "Whoa dude, chill lang, mali number. Wave check muna tayo."),
    ("📐", "Late ka na sa pagtawag AT mali pa number. Zero points."),
    ("🥠", "Ang tunay na hinahanap mo ay wala rito. Mali number."),
    ("🎬", "CUT! ...ay teka, hindi pala kunwarian 'to. Mali number talaga."),
    ("👴", "Noong panahon ko, wala pang cellphone! Pero ngayon, alam kong mali 'yang tinawagan mo."),
    ("🤡", "Uy is this a prank call? Kasi wrong number 'to, promise."),
    ("🕉️", "Ang kapayapaan ay nasa paghahanap ng tamang numero. Ito'y hindi iyon."),
    ("👨‍🍳", "Nasusunog ang ulam ko dahil sa tawag mo! At mali ka pa ng number, hay."),
    ("🛸", "Sino nagbigay sa'yo ng number ko?? May kumakalat na listahan?! Mali number 'to, layuan mo 'ko!"),
    ("🎀", "Thank you for calling! Unfortunately, hindi po kayo nasa tamang linya. Have a nice day!"),
    ("🏚️", "Wag mo kong tawagan, wala kang binabayarang renta dito. Mali number!"),
    ("🏆", "AND THE CALL... GOES TO... THE WRONG NUMBER! Ladies and gentlemen!"),
    ("💔", "Akala mo ba babalikan pa kita? Mali number, wag mo na 'ko tawagan."),
    ("🌪️", "Bagyo sa labas, at bagyo rin sa loob ng puso ko dahil sa maling tawag mo. Mali number."),
    ("😮‍💨", "Break time ko sana 'to. Mali number, buti pinahinga ako."),
    ("⚖️", "For the record, hindi ako ang taong hinahanap mo. Objection, mali number."),
    ("🎩", "Ah, hello po, ito po si... (giggles) ay mali number lang po pala."),
    ("📚", "Nag-aaral pa ko dito— wait, mali number lang naman. Sige, bye."),
    ("🙌", "OMG IS THIS MY IDOL?? ...ay hindi pala. Mali number lang. Sayang."),
    ("🛬", "Bagong uwi lang ako galing abroad, at ito ang una kong maling tawag dito. Mali number."),
    ("🕶️", "Ang misyon mo ay nabigo. Mali ang target. Mali number."),
    ("🔔", "TOLL TOLL— ay, tumawag ka pala. Mali number 'yan, anak."),
    ("🚕", "Traffic pa 'to tapos mali ka pa ng number, sus."),
    ("☕", "Order ko muna 'to ha... ay hindi pala order, tawag. Mali number, sorry!"),
    ("🎯", "Final answer ko: MALI NUMBER 'YAN. Tama ba, host?"),
    ("🎓", "Anak ko nga pala nag-topnotch sa board exam! Pero ikaw, mali number ka dito."),
    ("🌙", "Graveyard shift pa 'to... at mali ka ng number, buti nagising ako."),
    ("💬", "beep boop, hindi ako ang AI na hinahanap mo. Mali number, carry on."),
    ("🖐️", "*SLAP SOUND* Bakit mo ko tinawagan?! Mali number, hindi ako siya!"),
    ("📴", "Paumanhin, pakibigyang pansin: mali po ang inyong nadayal na numero."),
    ("🍢", "Tahoooo! ...ay teka, tawag lang pala 'to. Mali number, wala akong ganito dito."),
    ("🥀", "Kung ikaw talaga ang naghahanap sa akin, sana totoo. Pero mali number lang pala. Paalam magpakailanman."),
    ("😶", "...mali number. (Wala nang iba pang sasabihin.)"),
]

assert len(WRONG_SCRIPTS) == 100, len(WRONG_SCRIPTS)
